permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: pygments

kramdown:
  input: GFM

# Author Info 
author: 
  name: Simbazz 
  email: simbazz2101@gmail.com
  link: http://simbazz.info
  github:

# Site Info 
title: Simbazz's Blog 
description: Who is Simbazz? 
url: http://simbazz.info
rss_url: 

# Avatar & Favicon
avatar: /assets/img/simbazz_profile.png
favicon: /assets/img/simbazz_profile.png

# Google Analytics Set 
ga:
  id: UA-60793644-1
  url: simbazz.info 

# Disqus Set 
disqus:
  shortname: simbazzinfo
